name       : libwandio
version    : 4.0.0
release    : 3
source     :
    - https://research.wand.net.nz/software/wandio/wandio-4.0.0.tar.gz : f6d9c81c1ad0b7a99696c057fb02e5c04a9c240effd6bf587a5b02352ce86a9f
license    : LGPL-3.0-or-later
component  : programming.library
summary    : An API for reading and writing to files using a variety of compression  methods.
description: |
    Libwandio is a software library written in C that provides an API for transparently reading from and writing to files using a variety of supported compression methods.
builddeps  :
    - pkgconfig(libcurl)
    - bzip2-devel
    - libpth
    - lzo-devel
setup      : |
    %configure \
        --disable-static \
        --with-bzip2 \
        --with-http \
        --with-lzma \
        --with-lzo \
        --with-zlib
build      : |
    %make
install    : |
    %make_install
